### ISSUE TITLE
[flatpak] App doesn't show window when launched

### ISSUE THREAD

**Issue by hanaral** [hezral/clips#1]
Maybe I'm missing something, but I can't get it run outside the commandline

**Comment by hanaral** [comment]
@hezral 
```
han@elementary-os:~/Documents/clips-master$ flatpak run com.github.hezral.clips 
Gtk-Message: 12:51:15.141: Failed to load module "pantheon-filechooser-module"
2021-05-22 12:51:15.213228 startup
Gtk-Message: 12:51:15.241: Failed to load module "canberra-gtk-module"
2021-05-22 12:51:15.248659 open_db
Found ClipsDB [(0, 'main', '/home/han/.var/app/com.github.hezral.clips/cache/com.github.hezral.clips/com.github.hezral.clips.db')]
^C
```
Here is the terminal output
I have no idea why it isn't opening, is there a keybind or something?

**Comment by hezral** [comment]
that's odd.. can you try to uninstall and remove the /home/han/.var/app/com.github.hezral.clips/ directory. 
Also, pull the latest from the repo, i added some directory checks so it doesn't fail if the dir didn't exist. 

you're using io.elementary.Platform for the runtime? i actually haven't tested that yet.

**Comment by hanaral** [comment]
It's still not running, even after:
- Uninstalling with `--delete-data`
- Removing com.github.hezral.clips from ~/.var/app
- Using `io.elementary.Sdk`
- Building from main

**Comment by hezral** [comment]
well i'm stumped :) 

can you try installing it natively using meson

and which OS are you trying this on?

**Comment by hezral** [comment]
i just built it on Hera and it's working too.

**Comment by hanaral** [comment]
@hezral Before I test any of this, could you just tell me if there is a possibility that there are some required folders, because I have my home dir. locality set to japanese

**Comment by hanaral** [comment]
Native build does nothing too:
```
han@elementary-os:~/Documents/clips/build$ com.github.hezral.clips 
Gtk-Message: 17:20:39.583: Failed to load module "pantheon-filechooser-module"
2021-05-23 17:20:39.637665 startup
2021-05-23 17:20:39.670756 open_db
Found ClipsDB [(0, 'main', '/home/han/.cache/com.github.hezral.clips/com.github.hezral.clips.db')]

```
I'm using Odin Early Access

**Comment by hezral** [comment]
it doesn't require any additional folders other that the cache folder. 
can you share how you've set the locality to japanese? maybe i can try to reproduce that. 

if there are errors, it would show on the command line. so nothing after u launch it again from the desktop launcher right?

i'm on Odin Early Access too.

**Comment by hezral** [comment]
Ok, i just spin up a new Odin fresh install, and it works as well for flatpak.
it might be something with your setup. Are you able to try it on a fresh Odin install with no customization?

Hera
flatpak: OK
native: OK

Odin Early Access:
flatpak: OK
native: OK

**Comment by hanaral** [comment]
@hezral running both native and the flatpak version does something interesting with `--debug` enabled and I try to copy something:
han@elementary-os:~/Documents$ flatpak run com.github.hezral.clips --debug
```
Gtk-Message: 08:34:04.555: Failed to load module "pantheon-filechooser-module"
running in debug mode
waiting for clipboard event
Traceback (most recent call last):
  File "/app/share/com.github.hezral.clips/clips/clips_supported.py", line 100, in get_clipboard_contents
    print("Active App:", utils.get_active_app_window())
  File "/app/share/com.github.hezral.clips/clips/utils.py", line 243, in get_active_app_window
    all_apps = get_all_apps()
  File "/app/share/com.github.hezral.clips/clips/utils.py", line 195, in get_all_apps
    with open(desktop_file_path) as file:
UnboundLocalError: local variable 'desktop_file_path' referenced before assignment
```

**Comment by hezral** [comment]
that's for the debugging clipboard events but it does point out that the utils couldn't ready one of the directories. 

can you check if any of these folders are missing

/usr/local/share/applications
/var/lib/snapd/desktop
/var/lib/flatpak/exports/share/applications
~/.local/share/flatpak/exports/share/applications
~/.local/share/applications

also did u change anything on the flatpak manifest for the directory permissions?

**Comment by hezral** [comment]
@hanaral also any chance you can try on a fresh install, no customization?

**Comment by hanaral** [comment]
@hezral Yup, just did it and it's fixed. I really hope this was a one off thing because of something in the Early Access (for elementary's sake, I wouldn't want this to be a common issue)
Anyway great work with the app, I'll open some issues for other stuff now that I can test 
I'll close this, but it could be reopened if it wasn't a one-time thing

**Comment by hezral** [comment]
thanks, i'm stil curious what the issue was. 
Can you share how you configured locality for japanese?
I can read/write japanese too so i can test it

**Comment by hanaral** [comment]
I changed it via the locality plug, I mean locality as in the system's own underlying language for directory names and other stuff that setting your user's language doesn't change. It's messed with apps like zoom in the past which even as a flatpak are hardcoded to dump stuff in ~/Documents even if you instead only have a folder called ~/ドキュメント

**Comment by hezral** [comment]
that might be it. i'll need to relook at this. the paths that Clips reads are all system paths with user cache path which i see is not in japanese. 

btw, tested by setting language to Japanese and it worked . 

![image](https://user-images.githubusercontent.com/762735/119488354-03feca00-bd8d-11eb-9b48-0ba33b60c115.png)

**Comment by hanaral** [comment]
Very odd indeed.
The issue persisted no matter whether it was native or flatpak - so I still think it must've been something in my home dir (I probably should've seen whether it was the same on a new user)
