### ISSUE TITLE
How to setup shortcut?

### ISSUE THREAD

**Issue by Hedronmx** [hezral/clips#11]
I thought super + ctrl + C was the shortcut but I cant seem to open it via shortcut.

**Comment by hezral** [comment]
Hi, due to the app is now in Flatpak, shortcuts will have to be done manually. 
There is a button that will take you to the Settings page for the OS to set it up. Let me know.

**Comment by Hedronmx** [comment]
Got it working thank you!

**Comment by hezral** [comment]
it's not actually related to the shortcut. it's how the GTK code works, in the docs it says that it brings it to focus but it doesn't really do that. I haven't found a method that works, but i'll revisit it.

**Comment by hezral** [comment]
Well this was lucky, i had this fix already, i'll push a new release soon.

**Comment by ckruse** [comment]
Great news!
