### ISSUE TITLE
Automatically close app when focus is lost

### ISSUE THREAD

**Issue by Hedronmx** [hezral/clips#12]
I am loving your app, the only thing missing for me is that it does not close itself when focus is lost

**Comment by hezral** [comment]
I'm glad you like it. Can you check if this is enabled or not? This setting enables that feature. It may require to restart the app. 

![Screenshot from 2021-09-03 07 35 06](https://user-images.githubusercontent.com/762735/131929128-2ed55312-82b9-4fec-aa19-b5ae4818f2f8.png)

**Comment by Hedronmx** [comment]
It is enabled, it doesnt close itself when losing focus, I have to manually close it

**Comment by hezral** [comment]
correct, when its enabled it won't close when it looses focus. 
You have to disable it. 

I opted to now disable it by default to avoid people trying to figure out why it keeps on closing.

**Comment by Hedronmx** [comment]
The question here is, will the app keep working in the background? I ma comparing the behavior to this app
https://github.com/davidmhewitt/clipped

Where it would work as a background service, then you open the app with the shortcut and you get the clipped content and the app then goes back to being a background service.

**Comment by hezral** [comment]
Yes it will still work in the background.
