### ISSUE TITLE
Cmd + Ctrl + C is not working.

### ISSUE THREAD

**Issue by RicaBenhossi** [hezral/clips#13]
Don't know if it is a real problem or just I didn't undertood what this shortcut does, but the application did not open when I hit this combination. I suposed that it was the action it should do... I'm right?

I've tried to set a shortcut to the app in custom shortcuts, directly on elementray os, but it didn't work either. 

Congratulations for teh app... It's gorgeos.

**Comment by hezral** [comment]
Thanks for trying the app. 

Can you try setting this as in https://github.com/hezral/clips/issues/11 

I will update the help text for better clarity.

**Comment by RicaBenhossi** [comment]
\o/

Worked like charm.... Thank you!

**Comment by hezral** [comment]
Awesome, enjoy
