### ISSUE TITLE
Ctr + C does not seem to be working

### ISSUE THREAD

**Issue by atishdhu** [hezral/clips#14]
Copied contents does not appear in the app. Its still displaying no clips.

.....
Thank you for working on this app. Been waiting a long time for this on elementary OS.

**Comment by hezral** [comment]
thanks for trying the app. 

Can you post what output if your run it in terminal

flatpak run com.github.hezral.clips

**Comment by atishdhu** [comment]
Now its ok. The first time i opened the app it did not work. But after running it from the terminal, it started receiving the copied items. I will test it more and get back.

Thanks.

**Comment by hezral** [comment]
Thanks!
