### ISSUE TITLE
How to select which item is copied with the clipboard

### ISSUE THREAD

**Issue by chetbox** [hezral/clips#16]
This clipboard manager looks really nice, good job!

I'd like to replace my old clipboard manager with this but it's not entirely obvious to me how I might use it effectively with just the keyboard.

I have a keyboard shortcut for showing the app. I can navigate between the items with the arrow keys, but I can't find a way to put one of them into the clipboard with the keyboard.

The workflow I find useful is:
1. Keyboard shortcut to show clipboard history
2. Down arrow through list
3. Press return to paste, or possibly just put the selected item in the clipboard so that `Ctrl`+`V` will select it

Flycut on macOS does this really well. :)

A possibly related question: If I click an item there's a green ✅ that appears in the top right of the item indicating it's selected. What does that mean? I assumed that would mean it's now the thing in my clipboard buffer but that doesn't seem to be it.

**Comment by hezral** [comment]
Thanks for trying the app!

The "View Guides" section shows all the available keyboard shortcuts that can be used. 

There are quick copy for first 9 items using Alt+number key, and also each action button on the clip itself. 

Have a look :)

As for the ✅ it is for selecting clips to delete in mult select mode. it's covered in the guides as well.

**Comment by chetbox** [comment]
Okay, so I guess the workflow I'm after is possible but it's more key presses than I'm used to. Thanks!
