### ISSUE TITLE
When using arow keys and reach an end it can get to an unknown position

### ISSUE THREAD

**Issue by DevAlien** [hezral/clips#20]
For example if you have
```
- - -
- -
```
And you are in the thirs of of the first line, you press the down arrow, it does nothing but also you cannot move anymore until you press the UP arrow

**Comment by hezral** [comment]
this is due to the focus is moved betwen the clips (flowbox) area to the viewswitch (modeswitch) area. if you look closely you can see the focus highlight. 

i can disable the modeswitch to not grab focus since the views can be switch with the keyboard shortcuts Alt+left/right
