### ISSUE TITLE
how to completely uninstall Clips and their settings

### ISSUE THREAD

**Issue by diogopessoa** [hezral/clips#22]
package: Flatpak Clips
system: elementary OS 6 Odin

I changed some Clips settings and now it opens and closes at the same time.
I wanted to do a fresh clean install of Clips to get it back to default. 
Even though I uninstall and install again it still has the same problem.

Could you help me, please?

**Comment by hezral** [comment]
You can delete the folder in /home/yourusername/.var/app/com.github.hezral.clips

I think the uninstall does not remove the app configs etc if not explicitly selected. Did you uninstall from within AppCenter or commandline?

**Comment by diogopessoa** [comment]
Hi dear.

I managed to solve by deleting all Clips folders inside: '/var/lib/flatpak/' and ' /home/yourusername/.var/app/', and when installing again was working normally :)

I would like to suggest an improvement in the experience of using Clips.

**Steps to reproduce the problem:**
- When opening Clips, and after clicking on the copied item, Clips remains open overlapping the windows.

**Improvement suggestion:**
- Clips should automatically close after the item has been copied. 

Of course, this doesn't necessarily have to be the main behaviour. But it would be great to have this option available.

**Comment by diogopessoa** [comment]
> **Improvement suggestion:**
> 
>     * Clips should automatically close after the item has been copied.

Sorry, I found out now that this option already exists in Clips: **Persistent mode**. 
Disabling this option works the way I wanted it.

Thanks for making the Clips and for spending your time with me.  🙏

**Comment by hezral** [comment]
No problem. You actually don't need to uninstall the /va/lib/flatpak folder though.
