### ISSUE TITLE
Clips open and instantly closes

### ISSUE THREAD

**Issue by diogopessoa** [hezral/clips#23]
When I click to open Clips or execute the keyboard shortcut, Clips opens and closes instantly.
The apps in the Appcenter are all up to date.

What can I do?

**Comment by hezral** [comment]
Please open Terminal then run `flatpak run com.github.hezral.clips` and paste the output

**Comment by diogopessoa** [comment]
Follow the result:

2021-09-23 12:36:45.353784 startup
Gtk-Message: 12:36:45.397: Failed to load module "canberra-gtk-module"
2021-09-23 12:36:45.402796 open_db
Found ClipsDB [(0, 'main', '/home/diogo/.var/app/com.github.hezral.clips/cache/com.github.hezral.clips/com.github.hezral.clips.db')]
2021-09-23 12:36:45.881188 start load_clips
Gtk-Message: 12:36:46.226: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:36:46.228: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:36:46.348: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:36:46.350: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:36:46.448: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:36:46.455: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:36:46.461: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:36:46.463: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:36:46.556: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:36:46.558: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:36:46.560: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:36:46.562: Failed to load module "canberra-gtk-module"
2021-09-23 12:36:46.652410 finish load_clips
Gtk-Message: 12:36:46.785: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:36:46.787: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:36:46.870: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:36:46.872: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:36:46.967: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:36:46.972: Failed to load module "canberra-gtk-module"

**Comment by hezral** [comment]
Thanks. It looks like its running fine. 
Did you enabled hide on startup and disabled persistent mode?

**Comment by diogopessoa** [comment]
I had disabled hide on startup and persistent mode. 
The only one that was activated was always on top.

**Comment by hezral** [comment]
Can you quit and move this folder elsewhere /home/yourusername/.var/app/com.github.hezral.clips/config 
Then run the app again

**Comment by diogopessoa** [comment]
I did what you instructed and Clips opened again.
Then I changed the settings for this:

![clips_021-09-24 05-23-29](https://user-images.githubusercontent.com/12633864/134647001-92529358-c664-4564-a600-9e6429691f43.png)

After that Clips opened and closed instantly.
Again I restored the default Settings of Clips and left Persisnte Mode enabled. With this I realized that Clips works normally. 
Would that be a Bug?

I didn't want to use Clips with Persisnte Mode.

**Comment by hezral** [comment]
Persistent Mode when enabled means the Clips window will stay open util ESC key is pressed or the window is closed and Clips runs in the background. 

Disabling Persistent Mode means when the window focus changes from Clips to another app window, Clips automatically closes the window and runs in the background. 

Hide on startup is as it says, Clips window will not show when it ks first launched and it will run in the background until it is called via shortcut key or launching it via the launcher. 

It is intended behavior.

**Comment by diogopessoa** [comment]
I recorded a video to better demonstrate:

https://user-images.githubusercontent.com/12633864/134698253-a479c367-1b2d-4c6f-8b2b-764a99422058.mp4

when I deactivate Persistent Mode, Clips closes immediately without me doing any action.

**Comment by diogopessoa** [comment]
a screenshot before closing processes:

![Captura de tela de 2021-09-24 21 10 50](https://user-images.githubusercontent.com/12633864/134751230-57d8a847-629c-4105-8670-85fa178796b3.png)

and now after having closed all Clips processes:

https://user-images.githubusercontent.com/12633864/134751480-141115ba-c66c-4e67-9996-ef10f1f15d1e.mp4

The version 1.0.3 of Clips.

**Comment by hezral** [comment]
Thanks again. 
Can you uninstall, move the ~/.var/app/com.github.hezral.clips/config to another location, then install using the flatpak bundle here https://github.com/hezral/clips/actions/runs/1272106972

I updated the code for detecting window states which the persistent mode depends on.

**Comment by diogopessoa** [comment]
https://user-images.githubusercontent.com/12633864/134766925-21d39dc8-2a24-4f0a-a3e0-55f977bd3918.mp4

I did as you asked. Is there anything else I can do?

**Comment by hezral** [comment]
Thanks a lot. 
I'm not quite sure why its happening that way as i've tested on other machines and it works fine. Must be some conflict with your particular setup. 

For now i guess the workaround is to keep Persistent Mode enabled. 

If you don't mind, you could do a test with a new user account with no extra configs and see if it happens as well. 

Btw, the flatpak bundle you've installed won't auto update so after you're done testing, you need to install the one from AppCenter.

**Comment by diogopessoa** [comment]
I have news. 

I have identified that the Persistent Mode option, when not activated, has problems if Clips is not installed per-user applications.
in my case i installed Flatpak apps system-wide.
**but now when I installed Clips per-user, it worked**.

![Captura de tela de 2021-09-26 20-40-52](https://user-images.githubusercontent.com/12633864/134880921-1651d436-279a-4318-90a9-3ab741d2f022.png)

![Captura de tela de 2021-09-27 06-27-51](https://user-images.githubusercontent.com/12633864/134882450-0a786688-3293-4e1e-b738-d745a1638498.png)

**Comment by hezral** [comment]
I see. How did you install it as system?

**Comment by diogopessoa** [comment]
Just add the Flathub repository to the system:

    `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

After this, you can choose in AppCenter whether you will want to install in per-user or system-wide mode. In my case, I prefer to install all apps with 'flathub system', because my /home is separated on HDD, and the system / is on SSD which is much faster.

**Comment by hezral** [comment]
i see. i don't know why persistent mode would behave differently if its installed system-wide.. i need to research a bit. 
the code itself is only checking active window and Clip's window state.

**Comment by diogopessoa** [comment]
Now Clips works normally with Persistent Mode disabled or atived. 
Good work!

**Comment by hezral** [comment]
Cool, thanks for confirming. Next release will be out soon.
