### ISSUE TITLE
Cant Copy anything- cant decode codec utf-8

### ISSUE THREAD

**Issue by Hedronmx** [hezral/clips#27]
I get the following error every time i copy something

```
Traceback (most recent call last):
  File "/app/share/com.github.hezral.clips/clips/cache_manager.py", line 318, in update_cache
    data_tuple = clipboard_manager.clipboard_changed(clipboard, event)
  File "/app/share/com.github.hezral.clips/clips/clipboard_manager.py", line 83, in clipboard_changed
    active_app, active_app_icon = self.app.utils.get_active_appinfo_xlib()
  File "/app/share/com.github.hezral.clips/clips/utils.py", line 369, in get_active_appinfo_xlib
    all_apps = get_all_apps()
  File "/app/share/com.github.hezral.clips/clips/utils.py", line 203, in get_all_apps
    lines = file.readlines()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 67: invalid start byte

```

**Comment by hezral** [comment]
Can you try this daily build and see if the problem still exist?

https://github.com/hezral/clips/actions/runs/1333958172

**Comment by Hedronmx** [comment]
> may i know: what version are you running? Is this happen even after app restart? what type of content are you copying?

I am using 1.0.3 from appcenter



> Can you try this daily build and see if the problem still exist?
> 
> https://github.com/hezral/clips/actions/runs/1333958172

Just tried, same error. Funny thing its only happening on my laptop and not on my desktop.

**Comment by hezral** [comment]
Ok something specific on your laptop setup i think. 
Are you using a different language?

**Comment by hezral** [comment]
Thanks, i'll give another build for more logging. 

In the meantime can you try with a clean install? Move the ~/.var/app/com.github.hezral.clips somewhere, uninstall and install.

**Comment by Hedronmx** [comment]
I did and get the same error. Btw, I am trying to copy text. English text

**Comment by hezral** [comment]
Try this build and share the command line output after you copy something

https://github.com/hezral/clips/actions/runs/1345786037

**Comment by Hedronmx** [comment]
I cant attach it. But i did upload it to my owncloud 

https://drive.hedronmx.com/index.php/s/bKL3dIaFWNlqKLz
