### ISSUE TITLE
Excessive number of processes

### ISSUE THREAD

**Issue by Antolius** [hezral/clips#28]
After using the app for a while the number of spawned processes (mostly WebKitWebProces) seems excessive:

```shell
$ pstree 1668
flatpak-bwrap───flatpak-bwrap───com.github.hezr─┬─WebKitNetworkPr───232*[{WebKitNetworkPr}]
                                                ├─222*[WebKitWebProces───7*[{WebKitWebProces}]]
                                                └─229*[{com.github.hezr}]
```

`1668` is, in my case, Clips' root pid. This causes performance problems and ultimately fills up the maximum number of xorg clients, preventing future launches of any GUI apps (including Clips itself):

```shell
$ flatpak run com.github.hezral.clips 
Maximum number of clients reachedUnable to init server: Could not connect: Connection refused
Maximum number of clients reachedUnable to init server: Could not connect: Connection refused

(com.github.hezral.clips:2): Gtk-CRITICAL **: 22:56:17.127: gtk_clipboard_get_for_display: assertion 'display != NULL' failed
Traceback (most recent call last):
  File "/app/bin/com.github.hezral.clips", line 36, in <module>
    from clips import main
  File "/app/share/com.github.hezral.clips/clips/main.py", line 28, in <module>
    from .shake_listener import ShakeListener
  File "/app/share/com.github.hezral.clips/clips/shake_listener.py", line 9, in <module>
    from pynput import mouse
  File "/app/lib/python3.8/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/app/lib/python3.8/site-packages/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/app/lib/python3.8/site-packages/pynput/_util/__init__.py", line 76, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: ('failed to acquire X connection: Can\'t connect to display ":99.0": b\'Maximum number of clients reached\'', DisplayConnectionError(':99.0', b'Maximum number of clients reached'))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
 ```

Granted, I currently have a little over 1000 clips saved in the app. Most of it just snippets of text either from my local Code editor or from documentation sites online (which might contain some styling info like font color etc.). I could probably reduce the number of processes by deleting those clips, perhaps by running the housekeeping option in the Clips app itself. However, this is made a bit difficult by the fact that I can't currently launch the GUI.

This situation could probably be avoided by tweaking some of the housekeeping related settings. But it might be a good idea to put some restriction on the number of processes in the code itself, so that sloppy users such as myself don't shoot themselves in the foot with unfortunate combination of settings.

P.S. I otherwise love Clips! I can't imagine my workflow without a clipboard manager.

**Comment by hezral** [comment]
Hi, thanks for reporting this. This is interesting, i might need to rethink limiting the loading of the clips items. 
I'm guessing the 1000s of clips contains lots of html type contents?

You can for now, clean the cache manually, by moving out the files from ~/.var/app/com.github.hezral.clips/cache/com.github.hezral.clips
This will remove all clips. 

If you're familiar, you can also remove the clips you don't need through the sqlite database, this way you can still retain some of the clips

**Comment by hezral** [comment]
Did a bit of research, it seems webkitwebview is very hungry.. i need to rethink this. i have 250+ clips now, most are html clips and it started to crawl on a 6gb ram system.
