### ISSUE TITLE
Can't make payments on Appcenter

### ISSUE THREAD

**Issue by ghost** [hezral/clips#29]
[Here can be seen](https://imgur.com/ptfTSik), unfortunately I couldn't purchase this app.

**Comment by hezral** [comment]
Current state, new apps can't be monitized in AppCenter, but the elementary teams are working hard on this.

**Comment by cassidyjames** [comment]
@hezral an initial version of the Stripe token integration for the new AppCenter dashboard is live. You can now go to https://beta.developer.elementary.io/ and type your app URL in. There you will see a "Get a Stripe key" link to log in with Stripe. After you complete your on-boarding you will see the needed Stripe token. Please let me or @btkostner know if you have any questions!

**Comment by hezral** [comment]
@cassidyjames thanks, i'll try this. i have a PR open for https://github.com/elementary/appcenter-reviews/pull/233 for v1.0.8 should i withdraw that first and make a new release?

**Comment by hezral** [comment]
@cassidyjames i've submitted, will wait for the PR on the repo

**Comment by cassidyjames** [comment]
@hezral we're working on a copy update for that page; currently the PR does still need to be made manually. The important update was the stripe key on that page, though. :smile:

**Comment by hezral** [comment]
got it, thanks!

**Comment by hezral** [comment]
@cassidyjames @btkostner i've released with the new stripe key, but payment still fails. any idea what to check?

**Comment by btkostner** [comment]
The stripe key in your appstream file isn't included in our database. Go to developer.elementary.io, enter your all URL, and then connect Stripe. It will show a new "pk_live_" key that will work

**Comment by hezral** [comment]
actually that is what i did earlier and included in the new release. do you mean the new key is not in the db?

**Comment by btkostner** [comment]
Yes. The current key in master is not in the database

**Comment by hezral** [comment]
Ok, got it, thanks. 
Just wondering, i have other apps too which payment doesn't work since release, but they were all published before 6.0 release. Is it possible the key also not in the db?

**Comment by btkostner** [comment]
If it was enabled in houston, the key should have been copied over when we migrated, but if you’re getting payment issues, chances are it’s because the key isn’t in the database. You can use your newly generated key in all your other apps and it should work.
