### ISSUE TITLE
Weird copy content on https://javascript.info/

### ISSUE THREAD

**Issue by marcinjahn** [hezral/clips#30]
I just installed Clips on Fedora 35. I'm using MS Edge as a browser. When I copy text in the top area of the website https://javascript.info/:
![image](https://user-images.githubusercontent.com/10273406/140177973-e4673a56-cf61-4f5a-b5e3-19e5e3713108.png)

Clips shows me this:
![image](https://user-images.githubusercontent.com/10273406/140178030-b6b3c304-af40-4408-8d81-2882c08de8fb.png)

When I try to copy that in Clips (not as plain text) I get nothing - empty string.
When I try to copy that as plain text, I get:

```
<span style="color: rgb(255, 255, 255); font-family: BlinkMacSystemFont, -apple-system, &quot;Segoe UI&quot;, Roboto, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Main course contains 2 parts which cover JavaScript as a programming language and working with a browser. There are also additional series of thematic articles.</span>
```

**Comment by hezral** [comment]
Clips gets the content from the clipboard as-is, so if both the text and background color css is white, that's what happens. 
To avoid that, would mean to edit the clipboard contents itself, which would be tricky to maintain.

**Comment by hezral** [comment]
I've tested with replacing the css in the clip content, but this would alter the color styling, so that would be lost, and may introduce a different issue for others. as i said, it gets trickier to maintain

**Comment by marcinjahn** [comment]
Right, the issue is, that the copied text is not pasted at all, not even in white. I tried pasting it into the browser's URL bar, which ignores any styling. Nothing is pasted.

**Comment by hezral** [comment]
Ok that's a different issue and it has to do with the data type of when you copy out from clips. It can only set one type so when you copy a html content, the browser either can't understand it or tries to convert it and ends up with corrupted data. 

Right now i don't have a solution as my backend is using xclip and it can't set multiple content types for copying to the clipboard.
