### ISSUE TITLE
CTRL+C should copy the selected block

### ISSUE THREAD

**Issue by marcinjahn** [hezral/clips#31]
I find it weird that CTRL+C does not copy the selected block in the app. Instead, ALT+C seems to do it. I think it is not a good idea to require users to learn a new shortcut to copy a block when CTRL+C is a natural choice.

Btw, I think the app should have a way to change the shortcuts. It would solve this problem.

**Comment by hezral** [comment]
Thanks for the feedback, i was concerned early on and didn't use CTRL to avoid clashing with system shortcuts, i've just tested with CTRL and it seems to be fine now. 

Updated via https://github.com/hezral/clips/commit/b07a768333a8f351070a80c2ed92c566ad79890d

**Comment by hezral** [comment]
Will be in the next release

**Comment by hezral** [comment]
> Btw, I think the app should have a way to change the shortcuts. It would solve this problem. 
This will require time to implement, maybe for v2 :)
