### ISSUE TITLE
"Reveal cache file" should not be the first option in the actions bar

### ISSUE THREAD

**Issue by marcinjahn** [hezral/clips#32]
The order of actions is not right. The "Reveal cache file" would be used very rarely (if ever?), however it is first in the list. I guess the "View" or the copy actions should be first.

@hezral Let me know if you consider this to be a good change. I'd like to contribute to the project with this small improvement.

**Comment by hezral** [comment]
Thanks, it makes sense already made the changes :) https://github.com/hezral/clips/commit/c3e0cbc03a597595ecaf525bddf214ed8e67e05c

**Comment by hezral** [comment]
You can of course test it out from the automated build in https://github.com/hezral/clips/actions

**Comment by marcinjahn** [comment]
> Thanks, it makes sense already made the changes :) [c3e0cbc](https://github.com/hezral/clips/commit/c3e0cbc03a597595ecaf525bddf214ed8e67e05c)

Oh, shame, it was my motivation to try and do that myself to learn a bit about how to develop such apps myself. How could you! :D

**Comment by hezral** [comment]
Feel free to look around, though it might be a bit messy :)
