### ISSUE TITLE
If there's just one block on the list, it is smaller then it normally should be

### ISSUE THREAD

**Issue by marcinjahn** [hezral/clips#33]
If there's just one item in the list, it looks like this:

![image](https://user-images.githubusercontent.com/10273406/140179641-bac55fad-6fc3-41e5-9fd2-7669d8247868.png)

There is unneeded padding on the right.
If there are more items, the list starts to look as it should:

![image](https://user-images.githubusercontent.com/10273406/140179759-19f0317d-171a-401b-afe2-eb6e5a2552e4.png)

**Comment by hezral** [comment]
Thanks for the feedback. I struggled with this early in the development of Clips, ended up accepting this. It's actually the behaviour of the UI widget i'm using, and haven't found a workaound for it. I will keep this issue open in case i figure it out

**Comment by hezral** [comment]
Figured how to handle this, will be in next release, thanks for reporting this
