### ISSUE TITLE
Is this app for elementary os only?

### ISSUE THREAD

**Issue by generous-turd** [hezral/clips#38]
I cloned the repository, and ran the command that was given in the readme for a flatpak installation.
I got the following error:

```
error: io.elementary.Sdk/x86_64/6 not installed
Failed to init: Unable to find sdk io.elementary.Sdk version 6

```
I am on pop!_os 21.04

**Comment by dot1q802** [comment]
@generous-turd I'm also on Pop!_OS 21.04 and was able to get it working by adding the elementary flatpak remote and installing it from there. Though, I have to turn protected mode off for my copies to show up in the Clips menu.

    flatpak remote-add --if-not-exists --system appcenter https://flatpak.elementary.io/repo.flatpakrepo
    flatpak install com.github.hezral.clips

**Comment by generous-turd** [comment]
@dot1q802  thanks a lot! That works perfectly. I hope that this gets added to the README of this repository.

**Comment by hezral** [comment]
Thanks, yeah i should add that to the readme
