### ISSUE TITLE
Use Granite.validatedentry for password setup/entry

### ISSUE THREAD

**Issue by hanaral** [hezral/clips#4]
The current widget looks a little too tall (that's not that much of an issue) but more importantly it doesnlt use a symbolic icon for the tick, which shouldn't be a button if it's inside the box itself (the only exception I can think of is the refresh button in Files etc.)
I think copying the login greeter's arrow button could go nicely!

**Comment by hanaral** [comment]
Also use a tickbox for the password revealer, it's waaay more accessible!

**Comment by hezral** [comment]
thanks for this. i'll look into it

**Comment by hezral** [comment]
got the basics done, need to refactor the methods

![Screenshot from 2021-05-25 13 33 04](https://user-images.githubusercontent.com/762735/119444402-c3d42300-bd5d-11eb-98e2-f6f808da5241.png)

**Comment by hezral** [comment]
@hanaral you can try the latest version now. password ui completely revamped, also added a toggle for protected mode. Just move existing ~/.var/app/com.github.hezral.clips to somewhere first to test it fresh.

**Comment by hanaral** [comment]
The new look is much improved, nice work!
A couple of regressions I found were these:
- There is now an authenticate button in the 'old password' entry when changing the password, even though the apply button is at the bottom
- Clicking the 'set password' button when setting up a fresh install didn't do anything, but clicking 'skip protection' for some reason set it as if it worked
![Screenshot from 2021-05-27 21-44-20](https://user-images.githubusercontent.com/58219504/119896184-92fb1600-bf36-11eb-8270-443fede6f6f5.png)

Three non-critical nitpicks are:
- The bottom two buttons aren't using the normal elementary padding, but I get why you wanted it to be inline with the other widgets
- The password setup dialogue has a close button (in the top left) even though it's a dialogue with a cancel button at the bottom
- The button order is inverted to the elementary default:
![image](https://user-images.githubusercontent.com/58219504/119896291-bc1ba680-bf36-11eb-90ac-9dd16dd82b4e.png)

**Comment by hezral** [comment]
~~There is now an authenticate button in the 'old password' entry when changing the password, even though the apply button is at the bottom~~
It's the same for how the account change password works in the elementary Accounts switchboard. 
I've changed the behaviour depending on the context of when the password dialog is invoked. 

~~Clicking the 'set password' button when setting up a fresh install didn't do anything, but clicking 'skip protection' for some reason set it as if it worked~~
Thanks, fixed it now

~~The bottom two buttons aren't using the normal elementary padding, but I get why you wanted it to be inline with the other widgets~~
yeah, i changed it a bit now

~~The password setup dialogue has a close button (in the top left) even though it's a dialogue with a cancel button at the bottom~~
Initially i didn't put an ESC to dismiss and forgot to remove it after i did :) gone now

~~The button order is inverted to the elementary default~~
Was bugging me too, forgot to recheck

**Comment by hanaral** [comment]
Nice work!
