### ISSUE TITLE
[Feature Request] A minimal UI option and an "only text" mode.

### ISSUE THREAD

**Issue by veyselerden** [hezral/clips#44]
First of all, I -like most of us here- use elementaryOS and lack of a clipboard manager is painful for my use case so thank you very much for the app but there are some papercuts that I'd like to be smoothen, maybe some will agree with me. To begin with the UI is somewhat crowded with whole the icons and copied images. These are so useful features, yes, but sometimes while all I want is to copy & paste some text flood I copy one after another, I see a lot of icons of several apps which i've copied something from and images I've copied before makes my mind dizzy. So what i am suggesting is an option to have this kind of an "image-less" UI: 
![resim](https://user-images.githubusercontent.com/12845347/155810886-028f9b98-3eec-47f9-897f-588744b33967.png)

maybe one mode switch to have this kind maybe two option in the menu for "show copied images" and "minimal ui"? Anyways, I'd like to thank you again :)

**Comment by hezral** [comment]
Thanks for the suggestion and using the app!

I think its a good idea. For this mode, its probably doesn't make sense to list image type clips. 

Also Clipped was actually the inspiration for Clips :)

I'm working on something else right now so i will visit this once I'm done

**Comment by hezral** [comment]
Added toggle Ctrl+T to filter only plaintext and html types

You can test by building using latest source or wait for next release
