### ISSUE TITLE
Unable to open Clips on Fedora

### ISSUE THREAD

**Issue by rene-coty** [hezral/clips#46]
I installed the app on Fedora 35 using the repos provided, but when clicking the app icon or the 'Open' button from GNOME Software, nothing happens (no window...). I know the app was especially built for ElementaryOS, but given the fact it's a Flatpak, it should work on Fedora... Is it possible to fix this issue ? I really appreciate the concept of the app, although I am not a big fan of ElementaryOS

**Comment by hezral** [comment]
May i know if you're running wayland or x11? It doesn't work on Wayland due to how clipboard is handled and restricted

**Comment by rene-coty** [comment]
After verification I am running on Wayland 😅... so I guess we have the source of this issue..
I'll let you close the issue if you think it isn't a priority

**Comment by hezral** [comment]
No worries. At this point, i don't know if it will ever work because on wayland it depends on whether the compositor supports a specific protocol that lets clipboard manager works and that protocol isn't standard either. I am keeping an eye for now.
