### ISSUE TITLE
Provide release tags with .flatpak bundles

### ISSUE THREAD

**Issue by hanaral** [hezral/clips#6]
This should help distribution of pre-release versions to testers

**Comment by hezral** [comment]
i need to read up on this, any quick links?

**Comment by hanaral** [comment]
look at the building your first flatpak guide in the flatpak docs and it should tell you how to export to a local repo and then build a bundle from it

**Comment by hezral** [comment]
i think i misread this. basically you're saying to provide a .flatpak bundle in the releases right?
i got the action workflow working, just need to figure out how to get it to upload.

**Comment by hezral** [comment]
Haven't figure out an automated way yet, but i can do this manually for now
