### ISSUE TITLE
Submit to AppCenter

### ISSUE THREAD

**Issue by hanaral** [hezral/clips#7]
Would be quite cool to have this on the AppCenter

**Comment by hezral** [comment]
Planning to.. Just getting tied up with my day job ;)

**Comment by hezral** [comment]
Submitted

**Comment by hanaral** [comment]
@hezral In case you didn't know, you currently can only submit manually by opening a PR to the elementary/appcenter-reviews repo

**Comment by hezral** [comment]
@hanaral it's live in AppCenter now :)
