### ISSUE TITLE
Fails to launch

### ISSUE THREAD

**Issue by danrabbit** [hezral/clips#8]
After installing Clips using the bundle [here](https://github.com/elementary/appcenter-reviews/runs/3403015963), it fails to launch with this Terminal output:

```
flatpak run com.github.hezral.clips 
Traceback (most recent call last):
  File "/app/bin/com.github.hezral.clips", line 40, in <module>
    from clips import main
  File "/app/share/com.github.hezral.clips/clips/main.py", line 27, in <module>
    from .custom_shortcut_settings import CustomShortcutSettings
ModuleNotFoundError: No module named 'clips.custom_shortcut_settings'
```

**Comment by hezral** [comment]
Removed the code to use CustomShortcutSettings as it no longer works in flatpaks. 
Build successfull https://github.com/hezral/clips/actions/runs/1160602024

**Comment by cassidyjames** [comment]
@hezral yes, you'll need to create a new release so we can submit that to AppCenter.

**Comment by hezral** [comment]
Thanks @cassidyjames

**Comment by hezral** [comment]
Fixed with https://github.com/hezral/clips/releases/tag/1.0.1
