### ISSUE TITLE
Permissions seem aggressive

### ISSUE THREAD

**Issue by danrabbit** [hezral/clips#9]
While reviewing your app, I noticed that the flatpak sandbox permissions here seem pretty aggressive. Can you explain why your app needs:

all these filesystem permissions?
```
  - --filesystem=host
  - --filesystem=home
  - --filesystem=xdg-cache/com.github.hezral.clips
  - --filesystem=xdg-data
  - --filesystem=xdg-data/flatpak/exports/share
  - --filesystem=xdg-data/flatpak/app
  - --filesystem=/usr/share
  # - --filesystem=/usr/share/icons:ro
  - --filesystem=/usr/local/share/
  - --filesystem=/var/lib/flatpak/exports/share
  - --filesystem=/var/lib/snapd/desktop
  # needed for perfers-color-scheme
```

Access to the keyring?
```
  # keyring
  - --talk-name=org.freedesktop.secrets
```

GPU access?
```
  - --device=dri
```

Network access?
```
  - --share=network
```

**Comment by hezral** [comment]
Thanks, confirmed cahce permission isn't required. Confirmed with https://github.com/hezral/clips/actions/runs/1176132494

But for the keyring it is needed and i don't see it in the .var/app/<app>/ directory and when i removed it the code didn't work. 
I think it still uses the user's keyring session db
![Screenshot from 2021-08-28 07 45 27](https://user-images.githubusercontent.com/762735/131202306-b6ed907a-2902-422a-a246-a610aee9c272.png)

**Comment by hezral** [comment]
Closed with release in AppCenter
